# Generated by Django 5.2 on 2025-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginandauthentication', '0002_customdriver_tobenotified_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDriver',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
