# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(blank=True, default="", max_length=100)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("resource_type", "resource_id"),
                "unique_together": {("resource_type", "resource_id")},
            },
        ),
    ]
