# Generated by Django 5.2 on 2025-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destinations_list',
            field=models.JSONField(default=list),
        ),
    ]
