# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride_matching", "0002_route_destinations_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
