# Generated by Django 5.2 on 2025-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(default='uknown', max_length=255),
            preserve_default=False,
        ),
    ]
